### ISSUE TITLE
Filter messages over N bytes w/ error message

### ISSUE THREAD

**Issue by olirice** [supabase/walrus#11]
Document how to filter out wal2json messages that are > N bytes.

Do the filtering before passing through `cdc.apply_rls` and pass an error message

**Comment by w3b6x9** [comment]
@olirice thanks for creating this issue.

It would be great for devs to have access to the same message content, so they can surface the problem client-side to their users and diagnose the issue themselves. For example:

> {
>     "type": "INSERT",
>     "schema": "public",
>     "table": "todos",
>     "columns": [
>         {
>             "name": "id",
>             "type": "int8",
>         },
>         {
>             "name": "details",
>             "type": "text",
>         },
>         {
>             "name": "user_id",
>             "type": "int8",
>         }
>     ],
>     "commit_timestamp": "2021-09-29T17:35:38Z",
>     "record": null,
>.   "errors": ["changes surpass max size"]
> }

Credit to @abc3 for bringing this up!
