### ISSUE TITLE
Error when column type is quoted custom enum

### ISSUE THREAD

**Issue by w3b6x9** [supabase/walrus#31]
**Describe the bug**

I cannot listen to a table that has a column of type custom enum with double quotes.

**To Reproduce**

1. `CREATE TYPE "MOOD" AS ENUM ('sad', 'ok', 'happy');`
2. 
```sql
create table test (
  id bigint primary key,
  mood "MOOD"
);
```
3. Insert a row
4. Poll for changes

**Expected behavior**

I get back database changes without error.

**Actual behavior**

```sql
ERROR:  invalid input syntax for type json
DETAIL:  Token "MOOD" is invalid.
CONTEXT:  JSON data, line 1: ...:"bigint","value":1},{"name":"mood","type":""MOOD...
```

**Additional context**

wal2json issue: https://github.com/eulerto/wal2json/issues/224

**Comment by olirice** [comment]
Resolvable by upgrading to wal2json 2.4

**Comment by w3b6x9** [comment]
@olirice gonna keep this open until we upgrade all projects to wal2json 2.4

**Comment by olirice** [comment]
closing b/c up was completed (tracking the regression in a new issue #40 )
