### ISSUE TITLE
Append additional errors to errors array

### ISSUE THREAD

**Issue by w3b6x9** [supabase/walrus#36]
`errors` is currently of type `text[]` but errors are never appended to the array in `walrus--0.1.sql`. Is the plan to incorporate all errors into this `errors` array or should we change the type of `errors` to `text` and rename `errors` to `error`?

**Comment by olirice** [comment]
errors that act like exceptions e.g. permissions issues return immediately so those will always contain only 1 entry in the array

non-crashing errors like when the wal record exceeds a user defined size could be stacked, but we currently only have 1 error state that fits into this category

i'm happy to change it to a text field if you think the flexibility isn't going to be needed, lmk

**Comment by w3b6x9** [comment]
@olirice yep, that sounds good! just wanted some clarity around the different error states.
