### ISSUE TITLE
Enable filters for delete events

### ISSUE THREAD

**Issue by w3b6x9** [supabase/walrus#53]
# Feature request

## Is your feature request related to a problem? Please describe.

I want to be able to filter delete events based on primary key(s) and when replica identity is set to full, filter based on all columns available in database table.

## Describe the solution you'd like

For `DELETE` events:

- when I want to filter by a column that is not available in `old_columns`, then the subscriber is ignored.
- when replica identity is not full, only filters referencing the pk column(s) are respected.
- when replica identity is full, filters referencing any column in the table are respected.

## Additional context

- See comment: https://github.com/supabase/realtime/issues/265#issuecomment-1223768129

**Comment by roobox** [comment]
I am really desperately waiting for this feature!

**Comment by Zeulni** [comment]
Stumped upon that, need the same feature for my team!

**Comment by christophemenager** [comment]
Thanks for opening this issue @w3b6x9.

This should be at least clearly documented, it created a major in production for my mobile app...

**Comment by AndyLeezard** [comment]
Hello, are we getting any official fix on this matter soon?

**Comment by gsw85** [comment]
The UPDATE event ignoring filter as well

**Comment by Stiffjobs** [comment]
> The UPDATE event ignoring filter as well

Mine is working on UPDATE event

**Comment by georgii-ivanov** [comment]
Can we just filter by old record ID? So we know it, just implementing that filter would be helpful

**Comment by alexeigs** [comment]
It basically means you can't listen to the deletion of any user records currently because you'd subscribe to all deletion events on this table across the entire user base, right? 

I hope there's a fix or a recommended workaround added to the documentation given it's a major challenge everyone using realtime capabilities may face.

**Comment by cphoover** [comment]
I really think that the limitations to realtime... such as this... such as the limitations on filtering multiple columns... such as the scaling issues related to listening to postgres_changes... should preclude supabase from being marketed as a realtime db...


These limitations really make using subscriptions to db changes useless for most real world applications.

**Comment by Dario-Ciceri** [comment]
To me with .stream(primaryKey: ['id']).inFilter('id', [1,2,3,4,5,6,etc...); it works or at least it would seem to ignore the events of what is not inside the filter... of course I would have preferred to set different behaviors for each event but for now I am content. However, I don't understand the problem since from what I understand RealtimeChannel and .stream() of SupabaseStreamBuilder are the same API, am I wrong?

**Comment by galaxyblur** [comment]
I simply cannot recommend Supabase as a realtime solution until this is fixed. This is a security issue, full stop.

**Comment by willwillems** [comment]
A quick status update for others running into this problem:
- [When replica identity is full and row level security is on the old_record columns are filtered to primary key info only.](https://github.com/supabase/walrus/pull/65#issue-1549095015)
- [Support added for filters on delete events](https://github.com/supabase/walrus/pull/76)

The docs are lagging behind a bit here, but you should be fine just running:
```
ALTER TABLE your_table REPLICA IDENTITY FULL;
```

**Comment by upnorth** [comment]
> Thanks, I'll try that! I just wish the Supabase team could be a bit more responsible at fixing annoying bugs like these.

I remembered it slightly wrong, this is my implementation:

```
  const clearClipboardItems = async () => {
    if (userId) {
      // First delete all items
      const { error: deleteError } = await supabase
        .from("clipboard_items")
        .delete()
        .match({ user_id: userId });
      
      if (deleteError) {
        console.error("Error clearing clipboard items:", deleteError.message);
        return;
      }

      // Then insert the clear marker
      const { error: insertError } = await supabase
        .from("clipboard_items")
        .insert([{ 
          content: "clipboard-sync: clear all", 
          user_id: userId 
        }]);

      if (insertError) {
        console.error("Error inserting clear marker:", insertError.message);
      }
    }
  };
```

which is used in the subscription like this:

```
if (newItem.content === "clipboard-sync: clear all") {
  setItems([]); // Clear all items when we receive the clear marker
}
```

**Comment by upnorth** [comment]
The clear marker is also actively checked for and ignored in the rendering of content. And will be removed along with everything else at the next clear.

**Comment by jepartageteam** [comment]
https://supabase.com/docs/guides/realtime/postgres-changes#delete-events-are-not-filterable

As stated by supabase, this is a current limitation provided by the way Postgres work... 

A correct way of handling this by using a ref locally in the same file, and compare it with the old data on the deleted event

e.g
`if (payload.eventType === 'DELETE' && payload.old.id === localRefId.current) {
// your delete code
}`
