### ISSUE TITLE
Support for `in` operator

### ISSUE THREAD

**Issue by bhvngt** [supabase/walrus#9]
Hi, I am eagerly waiting for this functionality for my project. Just curious if support for `in` operator is in the roadmap. It will be super handy if `in` is supported.

**Comment by olirice** [comment]
Yes "in" support is definitely on the roadmap

Here's the full list of operators being considered https://postgrest.org/en/latest/api.html#operators

**Comment by osaxma** [comment]
Hi @olirice 

What are the supported operators by walrus as of now? Is it only `eq`?

**Comment by olirice** [comment]
Here are the allowed equality operations
https://github.com/supabase/walrus/blob/6b6c3ec212e91f3c2a51fa6698c0209dd5208b20/sql/walrus--0.1.sql#L10
but the availability may be limited depending on which client lib you're using

**Comment by osaxma** [comment]
I'm using dart library, but I was told it was a real time limitation according to this comment:
 - https://github.com/supabase-community/supabase-dart/issues/90#issuecomment-1018324651

I'll share your comment in supabase/realtime#222 

Thank you!

**Comment by w3b6x9** [comment]
Closing this b/c it's been implemented: https://github.com/supabase/walrus/pull/63.

If you would like to use this in Realtime you can check out https://github.com/supabase/realtime/issues/401#issuecomment-1413111707.
